apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-user
  name: backend-user
spec:
  ports:
  - name: backend-user
    port: 8080
    targetPort: 8080
  selector:
    service: backend-user