apiVersion: v1
kind: Service
metadata:
  labels:
    app: udacity-frontend
  name: udacity-frontend
spec:
  ports:
  - name: udacity-frontend
    port: 8100
    protocol: TCP
    targetPort: 80
  selector:
    app: udacity-frontend
#  type: LoadBalancer