apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-frontend
  labels:
    service: udacity-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udacity-frontend
  template:
    metadata:
      labels:
        app: udacity-frontend
    spec:
      containers:
      - name: frontend
        image: anuragdhiman400/udagram-frontend:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80